export const spanishTranslations = {
  MOTORCYCLE: "Motocicleta",
  SCOOTER: "Pasola",
  "FOUR WHEELER": "Four Wheeler",
  AVAILABLE: "Disponible",
  SOLD: "Vendido",
  SETTLED: "Saldo",
  SEIZED: "Incautado",
  STOLEN: "Robado",
  ACTIVE: "Activo",
  INACTIVE: "Inactivo",
  BLACKLISTED: "En lista negra",
  UNKNOWN: "Desconocido",
  PENDING: "Pendiente",
  "IN PROGRESS": "En progreso",
  DELIVERED: "Entregado",
};
